# Community learning {#community}

The Internet is full of resources for learning and troubleshooting how to code, and those resources are created by communities of people: software developers, researchers, teachers, and learners. Here are some communities to engage with. 

```{r, echo=FALSE, message=FALSE}
## https://github.com/gadenbuie/tweetrmd

# devtools::install_github("gadenbuie/tweetrmd")
library(tweetrmd)
include_tweet("https://twitter.com/TheStephLocke/status/1214569802804662274", plain = TRUE)

# ## alternate way: 
# ## devtools::install_github('rstudio/webshot2')
# library(webshot2)
# tweet_screenshot("https://twitter.com/TheStephLocke/status/1289648352192270336")
# ## this is supposed to hyperlink the screenshot, not happening presently...
# tweet_screenshot(tweet_url("TheStephLocke", "1289648352192270336"))

```

**Twitter** is a powerful tool and resource for coding. This is where developers, users, teachers, and learners share what they are working on, where they are stuck, how they have solved challenges. It is a place for thoughtful conversations in the coding community. Some advice and examples in the Q&A part of [this Openscapes blog post](https://www.openscapes.org/blog/2019/08/22/user-keynote/). 

**Slack** is another powerful tool for communities, where folks can interact and learn how to become good teachers and mentors by engaging an a network. Why should we use Slack? Here are some [slides](https://docs.google.com/presentation/d/1ji-3hLYPs3yIEu7wqyRdkGanxdON84ypuq8lyL5Yf-I/edit#slide=id.p) and a blog [blog](http://lcolladotor.github.io/2018/06/19/using-slack-for-academic-departmental-communication/#.XqkFPG57nOR) to help answer that question (Hicks & Collado-Torres).


## Language-based communities {#community-language}

Open source coding languages are powerful and dynamic because of their communities of developers, users, teachers, and learners from diverse backgrounds. [The Carpentries](https://carpentries.org/) is a teaching and learning community that spans many coding languages, has all their material online available for self-paced learning, and has [many ways to get involved](https://carpentries.org/community/).

### R {#community-r}

The R community has many overlapping communities, many of which also have a presence on Twitter and use the [\#rstats hashtag](https://twitter.com/hashtag/rstats?lang=en). Some of these communities include: 

- [RStudio](https://rstudio.com)
- [rOpenSci](https://ropensci.org)
- [RLadies](https://rladies.org)

Additional Slack channels: 

- [R for Data Science (R4DS) Online Learning Community](https://www.rfordatasci.com/)

### Python {community-python}

Python's main Twitter hashtags are [\#pydata](https://twitter.com/hashtag/pydata?lang=en) and [\#python](https://twitter.com/hashtag/python?lang=en). Some communities to engage with:

- [pyOpenSci](https://www.pyopensci.org/)
- [Pangeo](https://pangeo.io/index.html)


<!---Gene Yeo's Slack learning channel --->

## Parkinsons Disease

- https://parkinsonsroadmap.org/gp2/bioinformatics

## Image.sc Forum {#community-imagesc}

The focus of [Forum.image.sc ](https://Forum.image.sc) is software-oriented aspects of scientific imaging, particularly (but not limited to) image analysis, processing, acquisition, storage, and management of digital scientific images. Community partners and conversations include ImageJ, CellProfiler, Napari, QuPath, and more!

## Neubias

[NEUBIAS](http://eubias.org/NEUBIAS/) (Network of EUropean BioImage AnalystS) is a community developing resources for bioimage analysts. Of particular interest is the [Academy @ Home](http://eubias.org/NEUBIAS/training-schools/neubias-academy-home/) training series. Of particular interest might be [interactive bioimage analysis with Python and Jupyter](https://www.youtube.com/watch?v=2KF8vBrp3Zw) (Parts 1 and 2).

## Build your own local community

Communities like RLadies enable you to create local meetups linked to the global network. You can also create local communities or lead local events. Here are some examples and ideas:

**Example communities**

- [Eco-data-science](http://eco-data-science.github.io/)
- [Our coding club](https://ourcodingclub.github.io/contact.html)


**Example events**

From [resblazblog](https://resbazblog.wordpress.com/ideas/):

- hacky hours
- tidy tuesday meetups
- hackathons 

## Other training opportunities

- https://neuromatch.io/academy/
this is a bit more neuroscience than ND (eg more on neurophysiology side than genomics/omics)
- https://tess.elixir-europe.org/about

## Further Reading

- Cereceda & Quinn. 2020. [A graduate student perspective on overcoming barriers to interacting with open-source software](https://doi.org/10.1139/facets-2019-0020), *Facets*
- Sansing. [Open Facilitation](- https://chadsansing.gitbooks.io/open-facilitation/content/chapter12.html)


