# NDCN Office Hours {#office-hours}

Here are a few blank examples of our agendas from Office Hours in 2020. These agendas were prepared ahead of time and participants contributed to notes throughout the live events. 


<table>
  <tr>
   <td><strong>Week</strong>
   </td>
   <td><strong>Date</strong>
   </td>
   <td><strong>Topic</strong>
   </td>
   <td><strong>Blank Agenda</strong>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
1</p>

   </td>
   <td><p style="text-align: right">
April 27; May 1</p>

   </td>
   <td>Intro to office hours: Good enough practices
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/1LMPRyOmxb1hutjL4xzG6xsNuf7wLBuV63nHDPwaH-ZA/edit?usp=sharing</span>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
2</p>

   </td>
   <td><p style="text-align: right">
May 4;  May 8</p>

   </td>
   <td>Open data science, R
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/1BOaltY3nfb3yGWoO_DPLOTR4OJh2Js5Ihdjtd_HSvUI/edit?usp=sharing</span>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
3</p>

   </td>
   <td><p style="text-align: right">
May 11;  May 15</p>

   </td>
   <td>GitHub
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/1Ysfeqt3q1yLRbMw9kQoeHvxnCpR374okFFS8Qna2VtM/edit?usp=sharing</span>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
4</p>

   </td>
   <td><p style="text-align: right">
May 18;  May 22</p>

   </td>
   <td>RMarkdown
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/1E6H-2O5KiRGQ6Ju9h4M_F-YVgiMIeF_7Oj6wMJM-Qw0/edit?usp=sharing</span>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
5</p>

   </td>
   <td><p style="text-align: right">
May 29</p>

   </td>
   <td>Hackathon: batch renaming files co-led by the Arenas Lab and Oliver Tam
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/15VHJTt8atfww8dlR8x8wHrPLBQaDvOrq4IV0HLK8q8w/edit?usp=sharing</span>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
6</p>

   </td>
   <td><p style="text-align: right">
June 1;  June 5</p>

   </td>
   <td>Python: How do you learn it?
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/17Lt0YUfqIDNqDBTN99rc9YEdwPiZaer0ae3_hI5eSrU/edit?usp=sharing</span>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
7</p>

   </td>
   <td><p style="text-align: right">
June 8;</p>

<p>
<p style="text-align: right">
June 12</p>

   </td>
   <td>Marks Lab Tools: EVcouplings python framework led by Kelly Brock; open discussion
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/1GNTFfWExWvw5GY1BPpTlGbglZSzs9DnXbxyKWGAyBcI/edit?usp=sharing</span>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
8</p>

   </td>
   <td><p style="text-align: right">
June 15; June 22</p>

   </td>
   <td>Napari python tool led by Nick Sofroniew
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/1WgZ4PS7SGZH1CFYaxU2LMfyvuC_y1-z4oSMZTY_ouyo/edit?usp=sharing</span>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
9</p>

   </td>
   <td><p style="text-align: right">
June 26; </p>

   </td>
   <td>Hackathon part 2: checking filenames co-led by the Arenas Lab and Oliver Tam
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/1eqHco9vuWPi9OdM2j9ZY8pRHFlRSnvVUZ7mOG1ugeFc/edit?usp=sharing</span>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
10</p>

   </td>
   <td><p style="text-align: right">
June 30</p>

   </td>
   <td>Hacky Hour, discuss hackathon
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/1KCicmEa9WYjI6pIHlU-ddHI2xCPFw73Ts-WSK167cKI/edit?usp=sharing</span>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
11</p>

   </td>
   <td><p style="text-align: right">
July 6 & July 10</p>

   </td>
   <td>Code Review led by Mike Keiser (UCSF) and Arathi Mani (CZI);  ntro GitHub Clinic
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/1j5r0cI67cfbTGKKJmlRTCCpz5h6hwmD1Xnc8GuJJ3Jk/edit?usp=sharing</span>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
12</p>

   </td>
   <td><p style="text-align: right">
July 15</p>

   </td>
   <td>Lab Hacks: Computational Onboarding at the NDCN Annual Meeting
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/1w0AFW-784biF2k7Fu82ictac8IP5qHqQ5AfupM_4QCM/edit?usp=sharing</span>
   </td>
  </tr>
  <tr>
   <td><p style="text-align: right">
13</p>

   </td>
   <td><p style="text-align: right">
July 20; July 24</p>

   </td>
   <td>Is my RNA-seq data any good? Led by Molly Hammell & Oliver Tam; Using Python through RStudio
   </td>
   <td><span style="text-decoration:underline;">https://docs.google.com/document/d/1IUd09kwnH5T-Q4O5olNfTjCe4fJaf9uiYa29uquOkak/edit?usp=sharing</span>
   </td>
  </tr>
</table>


