# Onboarding {#onboarding}

*Computational Onboarding has been a recurring theme: how do you help others get "on board" with lab practices and protocols as quickly as possible?*


**What is computational onboarding?**

Onboarding is a business/management term for how new employees "acquire the necessary knowledge, skills, and behaviors in order to become effective organizational members and insiders" ([Wikipedia](https://en.wikipedia.org/wiki/Onboarding)). In a research setting, computational onboarding is the set practices for your lab that set the tone for what is expected. These practices are about tools and social norms – it's as much about "here are our values and code of conduct" as it is about "we use these software tools and store our data in this place."

Computational onboarding is an opportunity to put your values forward, model the behavior you want to see in your group & in science (i.e. your lab, dept, campus, online). An important part of onboarding is talking about what shared practices should be in your lab, and building trust and buy-in between lab members. You must be intentional about this: it is critical for inclusion and belonging in the lab, and not perpetuating inequities. Instead of the skills you have when you come to the lab determining how you will be able to Do Science, have shared practices in the lab and paths to onboard new people to work that way as well. It is an opportunity to address and fight sexual harassment and structural racism in science. Having a Code of Conduct as part of onboarding documentation is a part of this.

Thinking about onboarding means developing a team mindset for computation and to focus on similarities rather the differences between research in your lab. Since many of us are never formally trained in computational skills, we are self-taught and often develop analytical habits we feel are personal. But there is an advantage to having group conventions. It saves time by reducing everyday friction and reinventing the wheel for computational analyses. It can also increase morale and fuel collaborations within your lab group. Shared practices should be balanced with the need to accommodate for different skills people come in with. For example, if someone is more efficient in python, you don’t want to force R. But you should discuss how to interoperate between the two.

Writing onboarding plans down in a document helps everyone be on the same page (literally). This should be co-created by your lab as an activity to increase awareness and buy-in of shared practices. And using open/cloud-based software that is accessible from any Internet browser can facilitate open/shared culture and promotes open science! Some examples:

  * How we work: [Pinsky Lab](https://github.com/pinskylab), Lab policies: [Bahlai Lab](https://github.com/BahlaiLab). Code of Conduct: [Keiser Lab](https://github.com/keiserlab/policy)
    * These are all Markdown files in a Lab's GitHub Organization homepage
  * Standard operating procedures (SOP): [Ocean Health Index](https://rawgit.com/OHI-Science/ohiprep/master/src/dataOrganization_SOP.html), [emLab](https://emlab-ucsb.github.io/SOP/), [FayLab Manual](https://thefaylab.github.io/lab-manual/)
    * Rmarkdown published as webpage or e-book
  * Weekly onboarding-centered lab meetings: [Wood Lab](https://docs.google.com/document/d/e/2PACX-1vQEN-hqEIvnddWNdpYdATzZIUgAFFzKzPCLm5ijjSQeViD6E4ExAbHXYyhQSF58SyJQrWR40i6P_h2u/pub)
    * Google Doc > File > Publish to the Web
  * Notice that all of these are public. Leverage online: not only easier to find but is welcoming: signals diversity and inclusion


<!---

What is Onboarding? 
Wikipedia: management/business jargon: "the mechanism through which new employees acquire the necessary knowledge, skills, and behaviors in order to become effective organizational members and insiders….Studies have documented that socialization techniques such as onboarding lead to positive outcomes for new employees. These include higher job satisfaction, better job performance, greater organizational commitment, and reduction in occupational stress and intent to quit."
What does Onboarding mean for research?
Traditionally: keys, desk, wet-bench protocols, etc
Computationally: what software we use, where we store data, 
Huge opportunities to establish shared practices, focus on diversity and inclusion
Means creating best lab practices & philosophy, and formalizing as document, and sharing via public software like github/google docs etc. to put your values forward and practice open science 
It's  for shared analytical practices, lab values and setting an inclusive tone

--->